# Generated by Django 3.0.5 on 2020-05-09 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200509_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 10, 27, 7, 425490)),
        ),
    ]
